# Tomcat
server:
  port: 18000

# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-doc
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml

--- # knife4j聚合配置
knife4j:
  enableAggregation: true
  # cloud模式
  cloud:
    # 是否启用
    enable: true
    # 网关地址
    gatewayUri: 127.0.0.1:8080
    # 需要聚合的服务集合
    routes:
      - name: 系统服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /system/v2/api-docs
      - name: 代码生成
        uri: ${knife4j.cloud.gatewayUri}
        location: /code/v2/api-docs
      - name: 资源服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /resource/v2/api-docs
      - name: 认证服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /auth/v2/api-docs
