spring:
  application:
    name: product-provider-9092

  cloud:
    nacos:
      discovery:
        # 配置 nacos 的服务地址
        server-addr: localhost:8847
        # 配置命名空间,可以用来区分不同的开发环境，比如 dev,local，等，默认是public，此处需要给 控制台上 命名空间ID 的值
        # namespace:
        # 配置 组，不同服务可以划分到一个组, 默认是 DEFAULT_GROUP
        # group:
        # 注册服务名，默认值就是获取spring.application.name的值
        service: product-provider
        # 配置集群，默认是 DEFAULT
        # cluster-name:
        # 设置元数据
        metadata:
          version: v1
          author: huan
server:
  port: 9092