spring:
  application:
    name: gateway-filter
  cloud:
    nacos:
      discovery:
        # 配置 nacos 的服务地址
        server-addr: localhost:8847
    gateway:
      httpclient:
        # 全局的连接超时，单位毫秒
        connect-timeout: 1000
        # 全局的响应超时，需要符合java.time.Duration规范
        response-timeout: 3s
      routes:
        - id: product-provider-01
          uri: lb://product-provider
          predicates:
            - Path=/product/findOne
          metadata:
            # 单个路由配置响应超时,单位毫秒
            response-timeout: 200
            # 单个路由配置连接超时,单位毫秒
            connect-timeout: 200
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 9103