spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 配置 nacos 的服务地址
        server-addr: localhost:8847
    gateway:
      routes:
        - id: product-provider # 名字唯一即可
          uri: lb://product-provider
          predicates:
            - RemoteAddr=127.0.0.1/16
      # true : 表示启用 gateway，默认就是 true
      enabled: true
#      discovery:
#        locator:
#          enabled: true

server:
  port: 9102