spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 配置 nacos 的服务地址
        server-addr: localhost:8847
    gateway:
      routes:
        - id: product-provider # 名字唯一即可
          uri: lb://product-provider
          predicates:
            - Cookie=token,tokenvalue\d+ # 表示 请求中必须存在一个 cookie 的key 是 token 的，且值必须是 `tokenvalue 后面加上一个数子`才匹配的上，否则匹配不上。
      # true : 表示启用 gateway，默认就是 true
      enabled: true
#      discovery:
#        locator:
#          enabled: true

server:
  port: 9102