spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 配置 nacos 的服务地址
        server-addr: localhost:8847
    gateway:
      routes:
        - id: product-provider # 名字唯一即可
          uri: lb://product-provider
          predicates:
            - Before=2020-11-01T11:05:08.020+08:00[Asia/Shanghai]
      # true : 表示启用 gateway，默认就是 true
      enabled: true

server:
  port: 9102