spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 配置 nacos 的服务地址
        server-addr: localhost:8847
    gateway:
      routes:
        - id: product-provider # 名字唯一即可
          uri: lb://product-provider
          predicates:
            - Host=**.gateway.com,{study}.baidu.com
      # true : 表示启用 gateway，默认就是 true
      enabled: true
#      discovery:
#        locator:
#          enabled: true

#  1、`**.gateway.com`：表示请求中的`Host`的值需要配置这种`ant`风格
#  2、`{study}.baidu.com`：`study`这个模版变量可以在`GatewayFilter`中获取到，
#  通过`ServerWebExchange.getAttributes().get(ServerWebExchangeUtils.URI_TEMPLATE_VARIABLES_ATTRIBUTE)`获取

server:
  port: 9102