spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 配置 nacos 的服务地址
        server-addr: localhost:8847
    gateway:
      routes:
        - id: product-provider
          uri: lb://product-provider
          predicates:
            - Weight=group1,8
        - id: user-consumer
          uri: lb://user-consumer
          predicates:
            - Weight=group1,2
server:
  port: 9102