version: '3'
services:
  #监控管理台服务
  monitor-admin:
    image: cike/admin:latest
    container_name: sc-monitor-admin
    restart: always
    networks:
      - sc-net
    ports:
      - 8022:8022
    env_file: .env
    environment:
      TZ: Asia/Shanghai