spring:
  application:
    name: user-consumer-9091
  cloud:
    nacos:
      discovery:
        # 配置 nacos 的服务地址
        server-addr: localhost:8847
        # 表示只订阅服务，而不注册服务
        register-enabled: false

# nacos 集成 ribbon
ribbon:
  nacos:
    enabled: true
server:
  port: 9091